### ISSUE TITLE
Whatsapp button doesn't works at Android device

### ISSUE THREAD

**Issue by cirofeitosa** [globocom/share-bar#10]
We're using this share-bar.
All buttons works, **except Whatsapp**. When touch, in mobile device, anything happens.
Anyone see this problem too?

*PS.: tested in Android 4.4.4, with Whatsapp installed as well.*

**Comment by clybob** [comment]
Thanks @cirofeitosa, this issue will be fixed on next release 3.0.8.

**Comment by clybob** [comment]
Fixed on release 3.0.8
