### ISSUE TITLE
NPM registry

### ISSUE THREAD

**Issue by edygar** [globocom/share-bar#18]
Given the recent popular trends in adopting node and `NPM` in frontend build tooling, it would be nice to have this lib on `NPM` Plugin Registry, I couldn't find it there even though the lib is manage as npm package.

Nice reference: http://t.co/AaMpzXSUWm

**Comment by rafaelfragosom** [comment]
Done - [share-bar](https://www.npmjs.com/package/@globocom/share-bar)
