### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by cirofeitosa** [globocom/share-bar#21]
Hello guys.

I'm using the latest version of share-bar. Anyway, is working as well. But every page appears that error at console:

`Error: <path> attribute d: Expected number, "…0-23 5-31 12l209z".
createSVG @ vendor.min.js:40
init @ vendor.min.js:40
ShareBar @ vendor.min.js:40 (anonymous function) @ app.min.js:2`

Where:
vendor.min.js = jQuery + Foundation + Share-bar
app.min.js = App init, like this:

`try {new ShareBar({'facebookAppId': 'x', 'networks': ['facebook', 'twitter', 'whatsapp', 'google', 'email']});} catch (e) {console.error(e);}`

Anyone knows this problem?

**Comment by mateuspontes** [comment]
@cirofeitosa There's a error with email.svg, it was introduced with commit f928d9 and fixed with d7afd3

**Comment by clybob** [comment]
Hi @cirofeitosa, thanks for reporting this error. Today we accepted a pull request to solve this problem, and we launched the 3.1.2 version. Special thanks to @mateuspontes again for help.
