### ISSUE TITLE
Feature request: Add Linkedin Button

### ISSUE THREAD

**Issue by brubrant** [globocom/share-bar#31]
Hi, thank you for this great plugin!

What do you think about adding Linkedin among the possible networks? The "content side" of LinkedIn has been growing a lot and I think it would be a great addition.

**Comment by rafaelfragosom** [comment]
@brubrant I think that's a great feature.

I'll discuss with to team to release this in a future release or feel free to send a PR.

**Comment by brubrant** [comment]
PR sent.

**Comment by raphamorim** [comment]
Closed with #32
